image:           cappero_laser_odom_diag_2020-05-06-16-26-03.png
resolution:      0.05
origin:          [ 0.0,  0.0, 0.0 ]
occupied_thresh: 0.8
free_thresh:     0.1
negate:          0
mode:            scale
