// Generated by gencpp from file srrg2_core_ros/ViewerBufferMessage.msg
// DO NOT EDIT!


#ifndef SRRG2_CORE_ROS_MESSAGE_VIEWERBUFFERMESSAGE_H
#define SRRG2_CORE_ROS_MESSAGE_VIEWERBUFFERMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace srrg2_core_ros
{
template <class ContainerAllocator>
struct ViewerBufferMessage_
{
  typedef ViewerBufferMessage_<ContainerAllocator> Type;

  ViewerBufferMessage_()
    : header()
    , size(0)
    , num_packets(0)
    , status(0)
    , data()  {
    }
  ViewerBufferMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , size(0)
    , num_packets(0)
    , status(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _size_type;
  _size_type size;

   typedef uint64_t _num_packets_type;
  _num_packets_type num_packets;

   typedef uint8_t _status_type;
  _status_type status;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> const> ConstPtr;

}; // struct ViewerBufferMessage_

typedef ::srrg2_core_ros::ViewerBufferMessage_<std::allocator<void> > ViewerBufferMessage;

typedef boost::shared_ptr< ::srrg2_core_ros::ViewerBufferMessage > ViewerBufferMessagePtr;
typedef boost::shared_ptr< ::srrg2_core_ros::ViewerBufferMessage const> ViewerBufferMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator1> & lhs, const ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.size == rhs.size &&
    lhs.num_packets == rhs.num_packets &&
    lhs.status == rhs.status &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator1> & lhs, const ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srrg2_core_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add7e000fddfec4b3922d4f8c99195b3";
  }

  static const char* value(const ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadd7e000fddfec4bULL;
  static const uint64_t static_value2 = 0x3922d4f8c99195b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srrg2_core_ros/ViewerBufferMessage";
  }

  static const char* value(const ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#ia generic viewer buffer message. it contains all the fields of a MemoryBuffer\n"
"#ia in this way we use ros to send serialized packets containing objects and commands\n"
"#ia those can be either:\n"
"#ia   - received, deserialized and passed through a qglVieweport\n"
"#ia   - received, deserialized and converted into RViz compliant stuff\n"
"\n"
"Header  header\n"
"uint64 size           #ia size in bytes\n"
"uint64 num_packets    #ia number of packets serialized in this buffer\n"
"uint8 status          #ia status of the buffer (Free=0, Read=1, Write=2, Ready=3)\n"
"uint8[] data          #ia actual buffer of stuff\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.size);
      stream.next(m.num_packets);
      stream.next(m.status);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ViewerBufferMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srrg2_core_ros::ViewerBufferMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "size: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.size);
    s << indent << "num_packets: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.num_packets);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRRG2_CORE_ROS_MESSAGE_VIEWERBUFFERMESSAGE_H
