// Generated by gencpp from file pick_e_delivery/setTooLongInterval.msg
// DO NOT EDIT!


#ifndef PICK_E_DELIVERY_MESSAGE_SETTOOLONGINTERVAL_H
#define PICK_E_DELIVERY_MESSAGE_SETTOOLONGINTERVAL_H

#include <ros/service_traits.h>


#include <pick_e_delivery/setTooLongIntervalRequest.h>
#include <pick_e_delivery/setTooLongIntervalResponse.h>


namespace pick_e_delivery
{

struct setTooLongInterval
{

typedef setTooLongIntervalRequest Request;
typedef setTooLongIntervalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setTooLongInterval
} // namespace pick_e_delivery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick_e_delivery::setTooLongInterval > {
  static const char* value()
  {
    return "32162b1483389f970edd3323d63a7978";
  }

  static const char* value(const ::pick_e_delivery::setTooLongInterval&) { return value(); }
};

template<>
struct DataType< ::pick_e_delivery::setTooLongInterval > {
  static const char* value()
  {
    return "pick_e_delivery/setTooLongInterval";
  }

  static const char* value(const ::pick_e_delivery::setTooLongInterval&) { return value(); }
};


// service_traits::MD5Sum< ::pick_e_delivery::setTooLongIntervalRequest> should match
// service_traits::MD5Sum< ::pick_e_delivery::setTooLongInterval >
template<>
struct MD5Sum< ::pick_e_delivery::setTooLongIntervalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick_e_delivery::setTooLongInterval >::value();
  }
  static const char* value(const ::pick_e_delivery::setTooLongIntervalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_e_delivery::setTooLongIntervalRequest> should match
// service_traits::DataType< ::pick_e_delivery::setTooLongInterval >
template<>
struct DataType< ::pick_e_delivery::setTooLongIntervalRequest>
{
  static const char* value()
  {
    return DataType< ::pick_e_delivery::setTooLongInterval >::value();
  }
  static const char* value(const ::pick_e_delivery::setTooLongIntervalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick_e_delivery::setTooLongIntervalResponse> should match
// service_traits::MD5Sum< ::pick_e_delivery::setTooLongInterval >
template<>
struct MD5Sum< ::pick_e_delivery::setTooLongIntervalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick_e_delivery::setTooLongInterval >::value();
  }
  static const char* value(const ::pick_e_delivery::setTooLongIntervalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_e_delivery::setTooLongIntervalResponse> should match
// service_traits::DataType< ::pick_e_delivery::setTooLongInterval >
template<>
struct DataType< ::pick_e_delivery::setTooLongIntervalResponse>
{
  static const char* value()
  {
    return DataType< ::pick_e_delivery::setTooLongInterval >::value();
  }
  static const char* value(const ::pick_e_delivery::setTooLongIntervalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_E_DELIVERY_MESSAGE_SETTOOLONGINTERVAL_H
