// Generated by gencpp from file pick_e_delivery/setWaitPackInterval.msg
// DO NOT EDIT!


#ifndef PICK_E_DELIVERY_MESSAGE_SETWAITPACKINTERVAL_H
#define PICK_E_DELIVERY_MESSAGE_SETWAITPACKINTERVAL_H

#include <ros/service_traits.h>


#include <pick_e_delivery/setWaitPackIntervalRequest.h>
#include <pick_e_delivery/setWaitPackIntervalResponse.h>


namespace pick_e_delivery
{

struct setWaitPackInterval
{

typedef setWaitPackIntervalRequest Request;
typedef setWaitPackIntervalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setWaitPackInterval
} // namespace pick_e_delivery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick_e_delivery::setWaitPackInterval > {
  static const char* value()
  {
    return "32162b1483389f970edd3323d63a7978";
  }

  static const char* value(const ::pick_e_delivery::setWaitPackInterval&) { return value(); }
};

template<>
struct DataType< ::pick_e_delivery::setWaitPackInterval > {
  static const char* value()
  {
    return "pick_e_delivery/setWaitPackInterval";
  }

  static const char* value(const ::pick_e_delivery::setWaitPackInterval&) { return value(); }
};


// service_traits::MD5Sum< ::pick_e_delivery::setWaitPackIntervalRequest> should match
// service_traits::MD5Sum< ::pick_e_delivery::setWaitPackInterval >
template<>
struct MD5Sum< ::pick_e_delivery::setWaitPackIntervalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick_e_delivery::setWaitPackInterval >::value();
  }
  static const char* value(const ::pick_e_delivery::setWaitPackIntervalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_e_delivery::setWaitPackIntervalRequest> should match
// service_traits::DataType< ::pick_e_delivery::setWaitPackInterval >
template<>
struct DataType< ::pick_e_delivery::setWaitPackIntervalRequest>
{
  static const char* value()
  {
    return DataType< ::pick_e_delivery::setWaitPackInterval >::value();
  }
  static const char* value(const ::pick_e_delivery::setWaitPackIntervalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick_e_delivery::setWaitPackIntervalResponse> should match
// service_traits::MD5Sum< ::pick_e_delivery::setWaitPackInterval >
template<>
struct MD5Sum< ::pick_e_delivery::setWaitPackIntervalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick_e_delivery::setWaitPackInterval >::value();
  }
  static const char* value(const ::pick_e_delivery::setWaitPackIntervalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_e_delivery::setWaitPackIntervalResponse> should match
// service_traits::DataType< ::pick_e_delivery::setWaitPackInterval >
template<>
struct DataType< ::pick_e_delivery::setWaitPackIntervalResponse>
{
  static const char* value()
  {
    return DataType< ::pick_e_delivery::setWaitPackInterval >::value();
  }
  static const char* value(const ::pick_e_delivery::setWaitPackIntervalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_E_DELIVERY_MESSAGE_SETWAITPACKINTERVAL_H
