// Generated by gencpp from file pick_e_delivery/Timeout.msg
// DO NOT EDIT!


#ifndef PICK_E_DELIVERY_MESSAGE_TIMEOUT_H
#define PICK_E_DELIVERY_MESSAGE_TIMEOUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_e_delivery
{
template <class ContainerAllocator>
struct Timeout_
{
  typedef Timeout_<ContainerAllocator> Type;

  Timeout_()
    : event()  {
    }
  Timeout_(const ContainerAllocator& _alloc)
    : event(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_type;
  _event_type event;





  typedef boost::shared_ptr< ::pick_e_delivery::Timeout_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_e_delivery::Timeout_<ContainerAllocator> const> ConstPtr;

}; // struct Timeout_

typedef ::pick_e_delivery::Timeout_<std::allocator<void> > Timeout;

typedef boost::shared_ptr< ::pick_e_delivery::Timeout > TimeoutPtr;
typedef boost::shared_ptr< ::pick_e_delivery::Timeout const> TimeoutConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_e_delivery::Timeout_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_e_delivery::Timeout_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_e_delivery::Timeout_<ContainerAllocator1> & lhs, const ::pick_e_delivery::Timeout_<ContainerAllocator2> & rhs)
{
  return lhs.event == rhs.event;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_e_delivery::Timeout_<ContainerAllocator1> & lhs, const ::pick_e_delivery::Timeout_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_e_delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pick_e_delivery::Timeout_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_e_delivery::Timeout_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_e_delivery::Timeout_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_e_delivery::Timeout_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_e_delivery::Timeout_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_e_delivery::Timeout_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_e_delivery::Timeout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6aea470b1ed54075e83032ee4be16538";
  }

  static const char* value(const ::pick_e_delivery::Timeout_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6aea470b1ed54075ULL;
  static const uint64_t static_value2 = 0xe83032ee4be16538ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_e_delivery::Timeout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_e_delivery/Timeout";
  }

  static const char* value(const ::pick_e_delivery::Timeout_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_e_delivery::Timeout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string event\n"
;
  }

  static const char* value(const ::pick_e_delivery::Timeout_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_e_delivery::Timeout_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.event);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Timeout_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_e_delivery::Timeout_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_e_delivery::Timeout_<ContainerAllocator>& v)
  {
    s << indent << "event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_E_DELIVERY_MESSAGE_TIMEOUT_H
