(cl:defpackage pick_e_delivery-srv
  (:use )
  (:export
   "SETTOOLONGINTERVAL"
   "<SETTOOLONGINTERVAL-REQUEST>"
   "SETTOOLONGINTERVAL-REQUEST"
   "<SETTOOLONGINTERVAL-RESPONSE>"
   "SETTOOLONGINTERVAL-RESPONSE"
   "SETWAITPACKINTERVAL"
   "<SETWAITPACKINTERVAL-REQUEST>"
   "SETWAITPACKINTERVAL-REQUEST"
   "<SETWAITPACKINTERVAL-RESPONSE>"
   "SETWAITPACKINTERVAL-RESPONSE"
  ))

